// This file is automatically generated. We add a runtime-safe fallback
// so the app doesn't crash when supabase env vars are not provided locally.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Export a top-level variable and assign it conditionally to avoid
// using `export` inside a block (which causes a syntax error).
export let supabase: any;

const REALTIME_RECONNECT_COOLDOWN_MS = 5000;
let lastRealtimeReconnectAt = 0;

const handleRealtimeHeartbeat = (status: string) => {
  if (status !== "disconnected") return;
  const realtime = supabase?.realtime;
  if (!realtime || typeof realtime.connect !== "function" || typeof realtime.isConnected !== "function") return;
  if (realtime.isConnected()) return;
  const now = Date.now();
  if (now - lastRealtimeReconnectAt < REALTIME_RECONNECT_COOLDOWN_MS) return;
  lastRealtimeReconnectAt = now;
  try {
    realtime.connect();
  } catch (error) {
    console.warn("[supabase realtime] reconnect failed", error);
  }
};

const attachRealtimeSubscribeLogging = (client: any) => {
  if (!client || typeof client.channel !== "function") return;
  const flag = "__realtimeSubscribeLoggingAttached";
  if (client[flag]) return;
  client[flag] = true;

  const originalChannel = client.channel.bind(client);
  client.channel = (name: string, opts?: any) => {
    const channel = originalChannel(name, opts);
    if (!channel || typeof channel.subscribe !== "function") return channel;

    const originalSubscribe = channel.subscribe.bind(channel);
    channel.subscribe = (callbackOrTimeout?: any, maybeTimeout?: number) => {
      const callback = typeof callbackOrTimeout === "function" ? callbackOrTimeout : undefined;
      const timeout = typeof callbackOrTimeout === "number" ? callbackOrTimeout : maybeTimeout;

      return originalSubscribe((status: any, err?: any) => {
        if (status === "CHANNEL_ERROR" || status === "TIMED_OUT") {
          const reason =
            err instanceof Error
              ? { message: err.message, name: err.name, stack: err.stack }
              : err ?? "unknown";
          console.error("[supabase realtime] channel subscribe issue", {
            status,
            topic: channel?.topic,
            reason,
          });
        }
        callback?.(status, err);
      }, timeout);
    };

    return channel;
  };
};

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      worker: true,
      heartbeatCallback: (status) => handleRealtimeHeartbeat(status),
    },
  });
  attachRealtimeSubscribeLogging(supabase);
} else {
  // Minimal fallback implementation used in development when env is missing.
  supabase = {
    auth: {
      async getSession() {
        return { data: { session: null } };
      },
      onAuthStateChange(_cb: any) {
        return { data: { subscription: { unsubscribe: () => {} } } };
      },
      async signInWithPassword() {
        return { error: { message: 'Auth not configured in development' } };
      },
      async signUp() {
        return { data: { session: null }, error: { message: 'Auth not configured in development' } };
      },
      async resend() {
        return { error: { message: 'Auth not configured in development' } };
      },
      async signOut() {
        return;
      },
    },
  };
}
