// This file is automatically generated. We add a runtime-safe fallback
// so the app doesn't crash when supabase env vars are not provided locally.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Export a top-level variable and assign it conditionally to avoid
// using `export` inside a block (which causes a syntax error).
export let supabase: any;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
} else {
  // Minimal fallback implementation used in development when env is missing.
  supabase = {
    auth: {
      async getSession() {
        return { data: { session: null } };
      },
      onAuthStateChange(_cb: any) {
        return { data: { subscription: { unsubscribe: () => {} } } };
      },
      async signInWithPassword() {
        return { error: { message: 'Auth not configured in development' } };
      },
      async signUp() {
        return { data: { session: null }, error: { message: 'Auth not configured in development' } };
      },
      async resend() {
        return { error: { message: 'Auth not configured in development' } };
      },
      async signOut() {
        return;
      },
    },
  };
}